export const AdminRoute = '/admin';
export const AdminUserDelete = AdminRoute + '/delete';
export const AdminUserProfileRoute = AdminRoute + '/profile';
export const AdminUserBookingsRoute = AdminRoute + '/booking';
export const AdminUserTransactionsRoute = AdminRoute + '/transactions';
export const AdminUserCompanionFindRoute = AdminRoute + '/companionfind';
export const AdminUserChatRoomRoute = '/userchatrooms';
export const AdminAcceptanceRoute = AdminRoute + '/accept'
export const AdminIssuesRoute = AdminRoute + '/issues';